In [14]:
import numpy as np

In [2]:
def sigmoid_fn(array):
    return 1/(1+np.exp(-(array)))

In [15]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
sigmoid_fn(a)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])

In [64]:
def si(p,r,t):
    return (p*r*t)/100

In [17]:
si(1000,2,3)

60.0

In [24]:
a = np.random.random(15)
a

array([0.34621482, 0.73208621, 0.67069963, 0.58264374, 0.69478528,
       0.29462413, 0.84560907, 0.9876336 , 0.74385048, 0.13659781,
       0.77897181, 0.73723899, 0.93987163, 0.28990212, 0.31212808])

In [29]:
a*100

array([34.62148189, 73.20862084, 67.06996346, 58.26437378, 69.47852819,
       29.4624128 , 84.56090705, 98.7633605 , 74.38504802, 13.65978128,
       77.89718067, 73.72389888, 93.98716259, 28.99021167, 31.21280829])

In [37]:
a= np.random.randint(1,100,15)      #or np.random.randint(1,100,size=15) or np.random.randint(1,100,size=(15))
a

array([53, 29, 89, 15,  7,  6, 16, 23, 95, 57,  3, 89, 25, 65, 25])

In [40]:
np.sort(a)  # or s = np.sort(a) 
            #    s

array([ 3,  6,  7, 15, 16, 23, 25, 25, 29, 53, 57, 65, 89, 89, 95])

In [41]:
np.sort(a)[::-1]     #s[::-1]


array([95, 89, 89, 65, 57, 53, 29, 25, 25, 23, 16, 15,  7,  6,  3])

In [42]:
b = np.random.randint(1,100,24).reshape(6,4)        #or b = np.random.randint(1,100,size=(6,4))
b

array([[ 1, 92, 96, 68],
       [71, 57,  8, 82],
       [21, 49, 69, 22],
       [40, 52, 75,  9],
       [62, 29, 83, 92],
       [16, 65, 86, 24]])

In [43]:
np.sort(b)            #by default axis is 1 means row's data is getting sorted

array([[ 1, 68, 92, 96],
       [ 8, 57, 71, 82],
       [21, 22, 49, 69],
       [ 9, 40, 52, 75],
       [29, 62, 83, 92],
       [16, 24, 65, 86]])

In [44]:
np.sort(b,axis=0)   # axis = 0 means column's data is getting sorted

array([[ 1, 29,  8,  9],
       [16, 49, 69, 22],
       [21, 52, 75, 24],
       [40, 57, 83, 68],
       [62, 65, 86, 82],
       [71, 92, 96, 92]])

In [45]:
np.sort(b,axis=1)

array([[ 1, 68, 92, 96],
       [ 8, 57, 71, 82],
       [21, 22, 49, 69],
       [ 9, 40, 52, 75],
       [29, 62, 83, 92],
       [16, 24, 65, 86]])

In [46]:
a

array([ 3,  6,  7, 15, 16, 23, 25, 25, 29, 53, 57, 65, 89, 89, 95])

In [47]:
np.append(a,100)

array([  3,   6,   7,  15,  16,  23,  25,  25,  29,  53,  57,  65,  89,
        89,  95, 100])

In [48]:
a[3] = 100

In [49]:
a

array([  3,   6,   7, 100,  16,  23,  25,  25,  29,  53,  57,  65,  89,
        89,  95])

In [50]:
b

array([[ 1, 92, 96, 68],
       [71, 57,  8, 82],
       [21, 49, 69, 22],
       [40, 52, 75,  9],
       [62, 29, 83, 92],
       [16, 65, 86, 24]])

In [78]:
b.shape

(6, 4)

In [79]:
b.shape[0]

6

In [80]:
b.shape[1]

4

In [81]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [82]:
y = np.arange(6,12).reshape(2,3)
y

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [83]:
np.concatenate((x,y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [84]:
np.concatenate((x,y),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [85]:
np.concatenate((x,y),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [51]:
a

array([  3,   6,   7, 100,  16,  23,  25,  25,  29,  53,  57,  65,  89,
        89,  95])

In [52]:
np.unique(a) 

array([  3,   6,   7,  16,  23,  25,  29,  53,  57,  65,  89,  95, 100])

In [53]:
a

array([  3,   6,   7, 100,  16,  23,  25,  25,  29,  53,  57,  65,  89,
        89,  95])

In [54]:
a.shape

(15,)

In [56]:
np.expand_dims(a,axis=0)

array([[  3,   6,   7, 100,  16,  23,  25,  25,  29,  53,  57,  65,  89,
         89,  95]])

In [57]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [58]:
np.expand_dims(a,axis=1).shape

(15, 1)

In [59]:
a

array([  3,   6,   7, 100,  16,  23,  25,  25,  29,  53,  57,  65,  89,
        89,  95])

In [60]:
a%2

array([1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [61]:
a//2

array([ 1,  3,  3, 50,  8, 11, 12, 12, 14, 26, 28, 32, 44, 44, 47],
      dtype=int32)

In [62]:
a%2==0

array([False,  True, False,  True,  True, False, False, False, False,
       False, False, False, False, False, False])

In [63]:
##where:-
a[a%2==0]

array([  6, 100,  16])

In [65]:
a

array([  3,   6,   7, 100,  16,  23,  25,  25,  29,  53,  57,  65,  89,
        89,  95])

In [66]:
np.where(a%2==0)  ## Imp to remember "where" function example.It returns the index of the elements which are divisible by 2

(array([1, 3, 4], dtype=int64),)

In [67]:
a[np.where(a%2==0)]  ## Imp to remember If we put the above code in array it will give us values instead of index

array([  6, 100,  16])

In [68]:
np.argmax(a)    ## It returns the INDEX of maximum value of an array

3

In [69]:
np.argmin(a)    ## It return the INDEX of minimum value of an array

0

In [77]:
np.argsort(a)  ## It first sorts the elements in ascending order and then returns the index of that elements

array([ 0,  1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  3],
      dtype=int64)

In [78]:
a[np.argmin(a)]

3

In [72]:
q = np.array([1,2,3,np.nan,4,np.nan,7])
q

array([ 1.,  2.,  3., nan,  4., nan,  7.])

In [102]:
np.isnan(q)                                           

array([False, False, False,  True, False,  True, False])

In [73]:
q[np.isnan(q)]                                          

array([nan, nan])

In [104]:
q[~np.isnan(q)]

array([1., 2., 3., 4., 7.])

In [105]:
sachin_tend = np.random.randint(1,100,10)
sachin_tend

array([20, 62,  4, 88, 27, 99, 91, 21, 68, 55])

In [106]:
sachin_tend[0] + sachin_tend[1] + sachin_tend[2] + sachin_tend[3] + sachin_tend[4]

201

In [107]:
np.cumsum(sachin_tend)

array([ 20,  82,  86, 174, 201, 300, 391, 412, 480, 535], dtype=int32)

In [108]:
np.cumsum(sachin_tend)[4]

201

In [109]:
np.cumprod(sachin_tend)

array([         20,        1240,        4960,      436480,    11784960,
        1166711040, -1203477760,   496770816,  -579322880, -1797987328],
      dtype=int32)

In [110]:
a

array([ 45,  23,  51, 100,  67,  88,  51,  83,  89,  18,  45,  45,  82,
        99,   6])

In [111]:
np.isin(a,[70,19,100])              

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False])

In [112]:
a[np.isin(a,[70,19,100])]

array([100])

In [123]:
index = np.where(np.isin(a, [70, 19, 100]))[0]   ### Where is used to know the index
print(index)                                  

[3]


In [124]:
#IMPORTANT CONCEPT:
#You could also go deeper and slice (if there are multiple values) like this:

indices = np.where(np.isin(a, [70, 19, 100]))[0]
for i in indices:
    print(f"Index {i} has value {a[i]}")

Index 3 has value 100


In [113]:
a[~np.isin(a,[70,19,100])]

array([45, 23, 51, 67, 88, 51, 83, 89, 18, 45, 45, 82, 99,  6])

In [114]:
np.put(a,[1,5,7],[200,300,400])   ## "put" is used to replace more than one elements(with 200, 300,400)
a                                 ##  of an array at a particular index(i.e. 1,5,7)

array([ 45, 200,  51, 100,  67, 300,  51, 400,  89,  18,  45,  45,  82,
        99,   6])

In [115]:
np.delete(a,[1,2,3])           ## It deletes the elements at specified index

array([ 45,  67, 300,  51, 400,  89,  18,  45,  45,  82,  99,   6])

In [116]:
np.clip(a,a_min=30,a_max=60)            

array([45, 60, 51, 60, 60, 60, 51, 60, 60, 30, 45, 45, 60, 60, 30])

In [117]:
a

array([ 45, 200,  51, 100,  67, 300,  51, 400,  89,  18,  45,  45,  82,
        99,   6])

In [118]:
np.flip(a)

array([  6,  99,  82,  45,  45,  18,  89, 400,  51, 300,  67, 100,  51,
       200,  45])

In [5]:
def si(p,r,t):
    return (p*r*t)/100

In [13]:
p = 1000
r= 2
t = 3
si(p,r,t)

60.0

SyntaxError: invalid syntax (3088396893.py, line 1)

In [79]:
a

array([  3,   6,   7, 100,  16,  23,  25,  25,  29,  53,  57,  65,  89,
        89,  95])

In [80]:
a[0] = 1000
a

array([1000,    6,    7,  100,   16,   23,   25,   25,   29,   53,   57,
         65,   89,   89,   95])