In [1]:
import numpy as np

In [2]:
a = np.array([3,4,7,8]) 
a

array([3, 4, 7, 8])

In [3]:
b = np.array([[3,7,9],[10,57,30],[10,78,5]])
b

array([[ 3,  7,  9],
       [10, 57, 30],
       [10, 78,  5]])

In [4]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [5]:
c.shape

(2, 3, 3)

In [6]:
a[2]

7

In [7]:
b[1,1]

57

In [8]:
c[0,2,1]

8

In [9]:
c[1,0,1]

11

In [10]:
a

array([3, 4, 7, 8])

In [11]:
a[0:3:]

array([3, 4, 7])

In [12]:
a[:]

array([3, 4, 7, 8])

In [13]:
a[::]

array([3, 4, 7, 8])

In [14]:
a[1::]

array([4, 7, 8])

In [15]:
b

array([[ 3,  7,  9],
       [10, 57, 30],
       [10, 78,  5]])

In [16]:
b[0]

array([3, 7, 9])

In [17]:
b[0,]

array([3, 7, 9])

In [18]:
b[,0]               # this will not work for column like above row concept

SyntaxError: invalid syntax (154628558.py, line 1)

In [19]:
a[::-1]

array([8, 7, 4, 3])

In [23]:
b[::-1]   ## IMPORTANT CONCEPT

array([[10, 78,  5],
       [10, 57, 30],
       [ 3,  7,  9]])

In [24]:
b[::,::-1] ## IMPORTANT CONCEPT

array([[ 9,  7,  3],
       [30, 57, 10],
       [ 5, 78, 10]])

In [25]:
b[::-1,::]  ## IMPORTANT CONCEPT

array([[10, 78,  5],
       [10, 57, 30],
       [ 3,  7,  9]])