In [1]:
import numpy as np

In [2]:
a = np.array([7,8,9,12,45])

In [3]:
a

array([ 7,  8,  9, 12, 45])

In [4]:
print(a)

[ 7  8  9 12 45]


In [5]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
a= np.array([[[1,2],[3,4],[6,7]]])
a

array([[[1, 2],
        [3, 4],
        [6, 7]]])

In [8]:
print(a)

[[[1 2]
  [3 4]
  [6 7]]]


In [9]:
print(a.shape)

(1, 3, 2)


In [10]:
a= np.array([[[1,2],[3,4],[6,7]]])
a

array([[[1, 2],
        [3, 4],
        [6, 7]]])

In [11]:
print(a.shape)

(1, 3, 2)


In [12]:
a=np.array([1,8,10,56,78])
a

array([ 1,  8, 10, 56, 78])

In [13]:
print(a.shape)

(5,)


In [14]:
print(a.itemsize)

4


In [12]:
print(a.dtype)

int32


In [17]:
b=np.array([[7,19,48],[10,58,90]])
b

array([[ 7, 19, 48],
       [10, 58, 90]])

In [18]:
c=np.array([[[7,30,50],[78,10,56],[32,45,67]]])
c

array([[[ 7, 30, 50],
        [78, 10, 56],
        [32, 45, 67]]])

In [19]:
print(b.shape)

(2, 3)


In [20]:
print(c.shape)

(1, 3, 3)


In [21]:
a=np.array([9,0,22])
a

array([ 9,  0, 22])

In [22]:
a=np.array([9,0,22],dtype=float)
a

array([ 9.,  0., 22.])

In [25]:
a=np.array([9,0,22],dtype=bool)
a

array([ True, False,  True])

In [26]:
d=np.arange(12).reshape(3,4)
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
e= np.arange(1,13,1)
e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [28]:
e = np.arange(1,13,1).reshape(3,4)
e

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
e= np.arange(1,13,1).reshape(2,3,2)
e

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [30]:
e=np.arange(1,13,1).reshape(3,2,2)
e

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [31]:
print(e.shape)

(3, 2, 2)


In [38]:
f= np.ones((3,3))               # By default ones create an array in float 
f                                    

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.array([[1,8],[49,29]])

array([[ 1,  8],
       [49, 29]])

In [43]:
np.array([[1,8],[49,29]]).shape   # If we dont save an array in a variable we have to write the whole syntax of creating an array then method after dot

(2, 2)

In [44]:
g= np.ones((3,3),dtype=int)      #Using dtype=int we can change float data type into int
g

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [46]:
h= np.zeros((3,3))
h

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
h = np.zeros((3,3),dtype=int)
h

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [49]:
np.linspace(5,10,4)

array([ 5.        ,  6.66666667,  8.33333333, 10.        ])

In [51]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
np.identity((5),dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])