In [1]:
import numpy as np

In [2]:
a= np.array([10,14,23,78,49,30])
a

array([10, 14, 23, 78, 49, 30])

In [3]:
print(a.ndim)

1


In [4]:
b= np.array([[69,40,58],[20,56,89],[10,4,47]])
b

array([[69, 40, 58],
       [20, 56, 89],
       [10,  4, 47]])

In [7]:
b.ndim
#print(b.ndim)

2

In [7]:
print(a.shape)

(6,)


In [8]:
print(b.shape)

(3, 3)


In [9]:
print(b.ndim)

2


In [10]:
print(a.itemsize)

4


In [11]:
print(b.itemsize)

4


In [12]:
print(a.dtype)

int32


In [14]:
b+10

array([[79, 50, 68],
       [30, 66, 99],
       [20, 14, 57]])

In [15]:
b%2==0

array([[False,  True,  True],
       [ True,  True, False],
       [ True,  True, False]])

In [8]:
b

array([[69, 40, 58],
       [20, 56, 89],
       [10,  4, 47]])

In [17]:
b%3                        # giving remainder

array([[0, 1, 1],
       [2, 2, 2],
       [1, 1, 2]], dtype=int32)

In [18]:
b//3                       # giving quotient

array([[23, 13, 19],
       [ 6, 18, 29],
       [ 3,  1, 15]], dtype=int32)

In [19]:
b+3

array([[72, 43, 61],
       [23, 59, 92],
       [13,  7, 50]])

In [20]:
b-3

array([[66, 37, 55],
       [17, 53, 86],
       [ 7,  1, 44]])

In [24]:
c= np.array([[45,60,10],[10,59,20],[13,39,60]])
c

array([[45, 60, 10],
       [10, 59, 20],
       [13, 39, 60]])

In [26]:
b+c

array([[114, 100,  68],
       [ 30, 115, 109],
       [ 23,  43, 107]])

In [27]:
b>c

array([[ True, False,  True],
       [ True, False,  True],
       [False, False, False]])

In [29]:
b>107

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [31]:
b[b>107]

array([], dtype=int32)

In [12]:
b

array([[69, 40, 58],
       [20, 56, 89],
       [10,  4, 47]])

In [33]:
b>47

array([69, 58, 56, 89])

In [10]:
b[b>47]

array([69, 58, 56, 89])

In [35]:
b.sum()

393

In [36]:
b.max()

89

In [37]:
b.min()

4

In [13]:
b.prod()

-1610690560

In [39]:
np.prod(b)

-1610690560

In [14]:
b.sum(axis=0)

array([ 99, 100, 194])

In [41]:
b.sum(axis=1)

array([167, 165,  61])

In [44]:
b.mean()

43.666666666666664

In [45]:
np.mean(b)

43.666666666666664

In [46]:
np.sum(b,axis=0)     # or b.sum(axis=0)

array([ 99, 100, 194])

In [47]:
np.sum(b)

393

In [48]:
np.sin(b)

array([[-0.11478481,  0.74511316,  0.99287265],
       [ 0.91294525, -0.521551  ,  0.86006941],
       [-0.54402111, -0.7568025 ,  0.12357312]])

In [52]:
np.median(b)

47.0

In [54]:
b.mean(axis=0)

array([33.        , 33.33333333, 64.66666667])

In [55]:
np.mean(b)

43.666666666666664

In [56]:
b.mean()

43.666666666666664

In [58]:
np.mean(b,axis=0)

array([33.        , 33.33333333, 64.66666667])

In [15]:
b.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [60]:
np.median(b)

47.0

In [61]:
np.median(b,axis=0)

array([20., 40., 58.])

In [16]:
d=np.random.random((3,4))
d

array([[0.49220675, 0.66028874, 0.38315662, 0.16168493],
       [0.60468527, 0.17365702, 0.63254257, 0.48333067],
       [0.27851861, 0.84389541, 0.83244882, 0.01365783]])

In [17]:
e=np.random.randint((3,4))
e

array([2, 1])

In [12]:
# Generate a 3x3 array of random integers between 1 and 10
f= np.random.randint(1, 10, size=(3,3))
f

array([[4, 6, 9],
       [4, 7, 9],
       [7, 1, 5]])