In [1]:
import numpy as np

In [4]:
arr_zeros = np.zeros(10) 
arr_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ndim(arr_zeros)

1

In [7]:
arr_zeros = np.zeros(10, dtype=int)
arr_zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
a = arr_zeros.reshape(2,5)  #If I don't save reshaped zero array in a vaiable and without saving it.... 
a                           #into variable a and find it's dimension using np.dim it will return 1 in output
                            #as reshape just change in shape temporarily(so it will return dimension of origional array) see In[23] and In[24] here I have changed 
                            #arr_zeros in 3D array but it's size is still 1 bcz arr_zeros is still 1D and it is
                            #showing arr_zeros dimension if I save it in any var then np.ndim(var) will return o/p 3

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [11]:
np.ndim(a)                           

2

In [53]:
arr_zeros.reshape(1,2,5)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [54]:
np.ndim(arr_zeros)

1

In [55]:
arr_zeros = np.zeros((3,2), dtype=int)

In [56]:
arr_ones = np.ones((3,2))
arr_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [57]:
arr_identity = np.identity(5)
arr_identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
np.ndim(arr_identity)

2

In [59]:
arr_identity2 = np.identity((5,2))
arr_identity2

TypeError: 'tuple' object cannot be interpreted as an integer

In [12]:
arr_identity2 = np.identity(5,5)        # or np.identity((5,5)) will also show error only np.identity(5) will work
arr_identity2

TypeError: Cannot interpret '5' as a data type

In [ ]:
arr_identity3d = np.identity(1,5,5)   # can't create identical 3d array
arr_identity3d

In [4]:
arr_int = np.arange(100,121)
arr_int

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120])

# Q.  arr = np.arange(1,13) Reshape this into a 3x4 matrix, Extract Second Row, Extract Last Row


In [3]:
arr = np.arange(1,13).reshape(3,4)
second_row = arr[1]                                     
last_column = arr[0:3:1,3]      # or   last_column = arr[:,-1] # or  last_column = arr[::,3] # or last_column =[::,3::]
print("Reshaped array:\n",arr)
print("second row:",second_row)
print("Last Column:",last_column)

Reshaped array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
second row: [5 6 7 8]
Last Column: [ 4  8 12]


# Q. Create an array of int from 1 to 10 then: a. Square each element b. Compute sum of the squared values c.Find the square root of each original element

In [16]:
arr_int1 = np.arange(1,11)
arr_int1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
b=arr_int1 ** 2                # or np.square(arr_int1)
b

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [18]:
np.sum(b)

385

In [ ]:
np.sqrt(arr_int1)

# Q. Boolean Indexing and Masking: Create an array of 20 random integers between 1 and 100 then: a. Print all the elements greater than 50 b. Replace all odd numbers with -1


In [5]:
arr_int2 = np.random.randint(1,101,size=20)
arr_int2

array([68, 61,  5, 82, 23, 79, 48, 43, 12, 73, 16,  2, 34, 35, 30, 63, 66,
       94, 55, 52])

In [6]:
arr_int2>50
a=arr_int2[arr_int2>50]
print("Elements greater than 50 are:",a)

Elements greater than 50 are: [68 61 82 79 73 63 66 94 55 52]


In [7]:
arr_int2[arr_int2 % 2 != 0]

array([61,  5, 23, 79, 43, 73, 35, 63, 55])

In [22]:
arr_int2[arr_int2 % 2 != 0] = -1
arr_int2

array([ 26,  60,  66,  -1, 100,  -1,  38,  18,  -1,  -1,  -1,  96,   8,
        -1,  12,  -1,  -1,  52,  20,  -1])

In [ ]:
arr_int2

# Q. Given two matrices:
    Compute the element wise addition and multiplication,
    Compute the matrix prod
    Transpose matrix a

In [12]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [13]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [14]:
a+b
print("Addition:\n", a+b)

Addition:
 [[ 6  8]
 [10 12]]


In [15]:
a*b
print("multiplication:\n", a*b)

multiplication:
 [[ 5 12]
 [21 32]]


In [16]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [17]:
a.T
print("Transpose of a:\n",a.T)

Transpose of a:
 [[1 3]
 [2 4]]


In [20]:
mean_row = np.mean(b,axis = 1)
print("Mean of each row:", mean_row)

Mean of each row: [5.5 7.5]


In [21]:
max_value_col = np.max(b, axis=0)
print("max_value_col:\n", max_value_col)

max_value_col:
 [7 8]


# a.Generate a 4x4 matrix of random floats b/w 0 and 1. b. set the random seed to 42 for reproducibility c. Replace all the values less than 0.5 with 0

In [22]:
arr_float = np.random.random(16).reshape(4,4)
arr_float

array([[0.93569019, 0.35673019, 0.06250045, 0.75023768],
       [0.23023426, 0.49396643, 0.76148937, 0.50325798],
       [0.77751458, 0.56862406, 0.15276285, 0.69805709],
       [0.79340841, 0.76044762, 0.71363944, 0.42489565]])

In [28]:
np.random.seed(42)
arr_float1 = np.random.rand(4,4)
arr_float1

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451]])

In [25]:
arr_float1[arr_float1<0.5]

array([0.37454012, 0.15601864, 0.15599452, 0.05808361, 0.02058449,
       0.21233911, 0.18182497, 0.18340451])

In [ ]:
arr_float1[arr_float1<0.5] = 0
print("Array after replacing value with 0:\n",arr_float1)

# Flattening and Sorting

In [29]:
arr_f = np.array([[12,5,7],[1,9,3]])
flattened = arr_f.flatten()
sorted_desc = np.sort(flattened)[::-1]
print("Original Array:\n",arr_f)
print("Flattened Array:", flattened)
print("Sorted in descending order:", sorted_desc)

Original Array:
 [[12  5  7]
 [ 1  9  3]]
Flattened Array: [12  5  7  1  9  3]
Sorted in descending order: [12  9  7  5  3  1]


In [30]:
y = np.arange(24).reshape(6,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [32]:
# Syntax to get number of rows of an array
no_rows = y.shape[0]
no_rows

6

In [33]:
# Syntax to get number of columns of an array
no_cols = y.shape[1]
no_cols

4

In [34]:
arr_sliced = y[::,0:2]
arr_sliced

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]])

In [35]:
arr_sliced1 = y[::,2:4]
arr_sliced1

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [36]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [37]:
arr_sliced2 = y[::,1:3]
arr_sliced2

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [38]:
arr_s1 = y[0:5:4,0:3:2]
arr_s1

array([[ 0,  2],
       [16, 18]])

In [39]:
arr_s1 = y[[0,4,5]][:,[0,2,3]]  ### It is combination of slicing and indexing #### MOST IMP MUST PRACTICE THIS KIND OF QUE 
arr_s1

array([[ 0,  2,  3],
       [16, 18, 19],
       [20, 22, 23]])

# Imp Concept:

In [47]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [40]:
a= y[0::2,0::3]
a

array([[ 0,  3],
       [ 8, 11],
       [16, 19]])

In [41]:
b = y[1::2,1:3]
b

array([[ 5,  6],
       [13, 14],
       [21, 22]])

In [42]:
c = np.hstack((a,b))
c

array([[ 0,  3,  5,  6],
       [ 8, 11, 13, 14],
       [16, 19, 21, 22]])

In [43]:
d=c.reshape(6,2)
d

array([[ 0,  3],
       [ 5,  6],
       [ 8, 11],
       [13, 14],
       [16, 19],
       [21, 22]])

In [44]:
y                                    

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [45]:
len(y)             ### It returns rows number

6

# The most imp steps and concept to clear complex indexing Must try

In [48]:
## We can also break the same indexing arr_s1 = y[[0,4,5]][:,[0,2,3]] step by step into this to understand it.
## Step 1:
e = y[[0,4,5]]
e                                   

array([[ 0,  1,  2,  3],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [49]:
## Step 2:
## Now our new array is e (or we can say var so we will use slicing and indexing on this array.
## In below operation e[Row indexing/slicing,Column indexing/slicing] so colon giving all the rows of e array and after comma...
## [0,2,3] giving col 0 2 and 3 using indexing

f = e[:,[0,2,3]]    ### here using syntax: var[row indexing,col indexing]    here var is e on which we have to perform indexing
f

array([[ 0,  2,  3],
       [16, 18, 19],
       [20, 22, 23]])

# Iteration:

In [ ]:
### It will iterate each row one by one:

for i in y:
    print(i)

# Fancy Indexing Que:

In [50]:
arr_ind = np.arange(24).reshape(6,4)
arr_ind

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [51]:
arr_ind[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

# Find out elements of arr_ind that are greater than 6 and divisible by 2

In [52]:
(arr_ind > 6) & (arr_ind % 2 == 0)

array([[False, False, False, False],
       [False, False, False, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [53]:
g = arr_ind[(arr_ind > 6) & (arr_ind % 2 == 0)]
g

array([ 8, 10, 12, 14, 16, 18, 20, 22])

In [54]:
### If we want we can reshape it
h =g.reshape(2,4)
h

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [55]:
## OR
arr_ind[(arr_ind > 6) & (arr_ind % 2 == 0)].reshape(2,4)

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [56]:
h % 3 != 0    ## Elements of h not divisible by 3

array([[ True,  True, False,  True],
       [ True, False,  True,  True]])

In [57]:
h[h % 3 != 0 ]

array([ 8, 10, 14, 16, 20, 22])

In [58]:
~(h % 3 ==0)   ## Elements not divisible by 3

array([[ True,  True, False,  True],
       [ True, False,  True,  True]])

In [59]:
h[~(h % 3 ==0)]

array([ 8, 10, 14, 16, 20, 22])

In [60]:
h[h % 3 ==0]     ## Elements of h divisible by 3

array([12, 18])

In [61]:
arr1 = np.arange(10,161,10).reshape(4,4)
arr1

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [ ]:
arr1[0:2,::]          # extract first two rows

In [ ]:
arr1[:,-1]   #extract last column

In [ ]:
arr1[:,3:]   #extract last column              ## ?????? Diff b/w above and current o/p as both are giving last col but first one is 1D and second is 2D

In [ ]:
arr1[1:3,1:3]

In [ ]:
# Reverse the order of rows (flip vertically)            ### Imp Concept
arr1[3::-1,::]                                           ### OR arr1[::-1,::]


In [ ]:
# Reverse the order of columns (flip horizontally)
arr1[::,3::-1]                                            ### OR arr1[::,::-1]

In [ ]:
## Get every other(alternate) element from the second row
arr1[1,[0,2]]          ## var[row,columns]

In [ ]:
#step1: 
a1 = arr1[1]
a1

In [ ]:
#step2:
a1[[0,2]]

In [ ]:
arr1[1:2,0::2]

In [82]:
arr1

array([[ 10,  20,  30,  40],
       [ 50,   0,   0,  80],
       [ 90,   0,   0, 120],
       [130, 140, 150, 160]])

In [63]:
# Extract diagonal elements:                                 ##### Most IMP Concept
diagonal_elements = []
for i in range(len(arr1)):
    diagonal_elements.append(arr1[i][i])
print(diagonal_elements)

[10, 60, 110, 160]


In [62]:
np.diagonal(arr1)

array([ 10,  60, 110, 160])

In [64]:
arr1[range(4),range(4)]

array([ 10,  60, 110, 160])

In [ ]:
y

In [ ]:
# Row wise max value 
y.max(axis = 1)    # Or np.max(y,axis =1)   

In [ ]:
# Row mean value
row_mean = y.mean(axis = 1)
row_mean

In [ ]:
# Replace max value in each row with row mean
max_indices = np.argmax(y, axis = 1)
max_indices

In [ ]:
# Row index
rows = np.arange(y.shape[0])
rows

In [ ]:
y[rows, max_indices] = row_mean
print("Array after replacing max value of rows with mean of row:\n",y)

In [65]:
arr1

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [66]:
# Get bottom right 2x2 sub matrix
arr1[2::,2::]

array([[110, 120],
       [150, 160]])

In [67]:
#IMPORTANT CONCEPT
#Replace the middle 2x2 with zeros
arr1[1:3, 1:3]

array([[ 60,  70],
       [100, 110]])

In [68]:
arr1[1:3,1:3] = 0
print("Array after replacing middle 2x2 with zeros:\n",arr1)
print("Now array is updated permanently after replacing with zeros!!!")

Array after replacing middle 2x2 with zeros:
 [[ 10  20  30  40]
 [ 50   0   0  80]
 [ 90   0   0 120]
 [130 140 150 160]]
Now array is updated permanently after replacing with zeros!!!


In [2]:
z = np.arange(1,101).reshape(10,10)
z

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [70]:
#Extract all even rows and odd columns
z[::2,1::2]

array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30],
       [42, 44, 46, 48, 50],
       [62, 64, 66, 68, 70],
       [82, 84, 86, 88, 90]])

In [71]:
new_z = z[7::,7::]
new_z

array([[ 78,  79,  80],
       [ 88,  89,  90],
       [ 98,  99, 100]])

In [72]:
np.flip(new_z)                             ## IMP CONCEPT

array([[100,  99,  98],
       [ 90,  89,  88],
       [ 80,  79,  78]])

In [6]:
z[-1:-4:-1,-1:-4:-1]                        ## IMP CONCEPT

array([[100,  99,  98],
       [ 90,  89,  88],
       [ 80,  79,  78]])

In [73]:
k = np.arange(3*4*5).reshape(3,4,5)
k

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [ ]:
# From a 3D array of shape (3,4,5) extract the last two elements of the last axis for every 2nd slice in the first axis
k[::2,:,-2:]

In [74]:
z

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [75]:
z[(z%3 ==0)&(z%5==0)]

array([15, 30, 45, 60, 75, 90])

In [76]:
# OR 
mask = (z%3 ==0)&(z%5==0)
z[mask]

array([15, 30, 45, 60, 75, 90])

# Checkboard

In [77]:
## Extract a checkerboard pattern(like a chessboard 1s and 0s) from z
z[::2,::2]

array([[ 1,  3,  5,  7,  9],
       [21, 23, 25, 27, 29],
       [41, 43, 45, 47, 49],
       [61, 63, 65, 67, 69],
       [81, 83, 85, 87, 89]])

In [78]:
z

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [79]:
## EXtract all rows where the third column is greater than 50
z[:,2]>50

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [80]:
z[z[:,2]>50]

array([[ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
### Flip both dimesions (equivalent to rotating 180 degree)
z[::-1,::-1]

In [7]:
### Extract diagonal from top right to bottom left
w[np.arange(10), np.arange(9,-1,-1)]

NameError: name 'w' is not defined

In [ ]:
##From a 4d array of shape (2,3,4,5), get the last 2 elements of every 3rd row from every matrix
c = np.random.randint(0,100, size=(2,3,4,5))
c

In [ ]:
c[:,:,::3,-2:]

In [ ]:
##flatten an array
a = np.array([[1,2],[3,4]])
a

In [ ]:
a.flatten()   ## np.flatten(a)   doesn't work                              


# Create a checkerboard pattern

In [84]:
print("CheckerBoard Pattern:")
x = np.zeros((8,8),dtype = int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

CheckerBoard Pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Create a 2D array of shape (a,b) with zeros using function and take shape(a,b) as parameter to function 

In [85]:
def arr3(x,y):
    return np.zeros((x,y), dtype =int)
    
a = 3
b = 2
arr3_f = arr3(a,b)
print("Random array is:\n", arr3_f)

Random array is:
 [[0 0]
 [0 0]
 [0 0]]


In [ ]:
###OR

In [86]:
def arr3(a,b):
    return np.zeros((a,b), dtype = int)

a = 3
b = 2
arr3_f = arr3(a,b)
print("Random array is:\n", arr3_f)

Random array is:
 [[0 0]
 [0 0]
 [0 0]]


In [ ]:
###OR