In [2]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
a = np.array([1,3,5,6])
a

array([1, 3, 5, 6])

In [4]:
b = np.array([[1,2,3],[4,8,9],[6,3,9]])
b

array([[1, 2, 3],
       [4, 8, 9],
       [6, 3, 9]])

In [5]:
np.ndim(b)

2

In [6]:
np.size(b)

9

In [10]:
np.shape(b)

(3, 3)

In [15]:
c = np.array([[[2,3],[5,6],[2,5]]], dtype=float)
c

array([[[2., 3.],
        [5., 6.],
        [2., 5.]]])

In [12]:
np.shape(c)

(1, 3, 2)

In [13]:
np.ndim(c)

3

In [14]:
np.itemsize(c)   # not correct syntax

AttributeError: module 'numpy' has no attribute 'itemsize'

In [70]:
c.itemsize  # correct syntax

8

In [5]:
d = np.arange(1,17).reshape(1,2,2,4)
d

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]]]])

In [6]:
np.ndim(d)

4

In [7]:
np.shape(d)

(1, 2, 2, 4)

In [8]:
e = np.arange(0,20,2, dtype = float)       #Imp Concept
e.reshape(2,5)

array([[ 0.,  2.,  4.,  6.,  8.],
       [10., 12., 14., 16., 18.]])

In [43]:
e = np.arange(0,20,2)
e

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [52]:
one = np.ones((4,4), dtype = int)
one

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [54]:
zero = np.zeros((4,5))
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [65]:
ls = np.linspace(1,10,6)
ls

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [66]:
ls.reshape(2,3)

array([[ 1. ,  2.8,  4.6],
       [ 6.4,  8.2, 10. ]])

In [67]:
ls1 = np.linspace(1,10,6, dtype = int)
ls1

array([ 1,  2,  4,  6,  8, 10])

In [68]:
ls1.reshape(3,2)

array([[ 1,  2],
       [ 4,  6],
       [ 8, 10]])

In [71]:
d

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]]]])

In [72]:
d>=7

array([[[[False, False, False, False],
         [False, False,  True,  True]],

        [[ True,  True,  True,  True],
         [ True,  True,  True,  True]]]])

In [73]:
d[d>=7]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [75]:
d%7

array([[[[1, 2, 3, 4],
         [5, 6, 0, 1]],

        [[2, 3, 4, 5],
         [6, 0, 1, 2]]]], dtype=int32)

In [76]:
d//7

array([[[[0, 0, 0, 0],
         [0, 0, 1, 1]],

        [[1, 1, 1, 1],
         [1, 2, 2, 2]]]], dtype=int32)

In [77]:
d%2==0

array([[[[False,  True, False,  True],
         [False,  True, False,  True]],

        [[False,  True, False,  True],
         [False,  True, False,  True]]]])

In [78]:
d[d%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [82]:
arr1 = np.array([[1,2],[3,6],[9,4]])
arr1

array([[1, 2],
       [3, 6],
       [9, 4]])

In [83]:
arr2 = np.array([[5,6,3],[3,7,9]])
arr2

array([[5, 6, 3],
       [3, 7, 9]])

In [84]:
dp = np.dot(arr1,arr2)
dp

array([[11, 20, 21],
       [33, 60, 63],
       [57, 82, 63]])

In [87]:
np.random.random(10)  # generating 1 row and 10 columns

array([0.85909068, 0.71685009, 0.18076376, 0.28241769, 0.94152726,
       0.98838289, 0.1745157 , 0.07963404, 0.77891231, 0.47644531])

In [14]:
rd = np.random.random((1,10))  # generating 1 row and 10 columns
rd

array([[0.72337747, 0.60507809, 0.41403014, 0.04990564, 0.64660824,
        0.6857279 , 0.02835901, 0.98050987, 0.08402916, 0.88411788]])

In [19]:
rf = rd.reshape(2,5)
rf

array([[0.72337747, 0.60507809, 0.41403014, 0.04990564, 0.64660824],
       [0.6857279 , 0.02835901, 0.98050987, 0.08402916, 0.88411788]])

In [17]:
rk = np.random.random((2,10))    #generating 2 rows and 10 columns
rk

array([[0.73513354, 0.73770572, 0.13076954, 0.37551241, 0.26281475,
        0.69886237, 0.13570518, 0.76273764, 0.80202375, 0.11050837],
       [0.77850873, 0.3068901 , 0.35126112, 0.86718428, 0.07364262,
        0.37329921, 0.3230528 , 0.96947747, 0.56121022, 0.56225264]])

In [20]:
np.round(rf)

array([[1., 1., 0., 0., 1.],
       [1., 0., 1., 0., 1.]])

In [21]:
np.floor(rf)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ceil(rf)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.sum(rf)

5.101743410019199

In [100]:
np.random.random((2,10))     # 2 means generating two rows and 10 columns

array([[0.68477071, 0.98756605, 0.48923574, 0.8976605 , 0.22795124,
        0.08624223, 0.57684889, 0.05297918, 0.76340242, 0.91753306],
       [0.28864208, 0.00513019, 0.50397923, 0.74001812, 0.74421763,
        0.90545646, 0.71645081, 0.91077027, 0.34908488, 0.37930896]])

In [102]:
np.array(rf, dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [109]:
d

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]]]])

In [105]:
d.max()

16

In [106]:
np.max(d)

16

In [111]:
np.max(d, axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])